# ===================================
# Filter Scope Definitions
# ===================================
scopes:
    year:
        label: awme.parking::lang.filters.year
        type: checkbox
        scope: ShowYear

    month:
        label: awme.parking::lang.filters.month
        type: checkbox
        scope: ShowMonth

    week:
        label: awme.parking::lang.filters.week
        type: checkbox
        scope: ShowWeek

    today:
        label: awme.parking::lang.filters.today
        type: checkbox
        scope: ShowToday