# ===================================
#  Relation Behavior Config
# ===================================

client:
    label: Cliente
    view:
        list: $/acme/user/models/role/columns2.yaml