# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Parking

# Model Form Field configuration
form: $/awme/parking/models/parking/fields.yaml

# Model Class name
modelClass: AWME\Parking\Models\Parking

# Default redirect location
defaultRedirect: awme/parking/parkings

# Create page
create:
    title: Crear Parking
    redirect: awme/parking/parkings/update/:id
    redirectClose: awme/parking/parkings

# Update page
update:
    title: Editar Parking
    redirect: awme/parking/parkings
    redirectClose: awme/parking/parkings
    form: $/awme/parking/models/parking/update_fields.yaml

# Preview page
preview:
    title: Preview Parking